# Generated by Django 4.1 on 2022-08-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_cv_imagecontact_imageindex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageContact',
        ),
        migrations.DeleteModel(
            name='ImageIndex',
        ),
    ]
