# Generated by Django 4.1 on 2022-08-14 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_delete_imagecontact_delete_imageindex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cv',
        ),
    ]
