# Generated by Django 4.1 on 2022-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_delete_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageContac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_portfolio/')),
            ],
        ),
    ]
