# Generated by Django 4.1 on 2022-08-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_imagecontac'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imageContac',
        ),
    ]
